### ISSUE TITLE
App Review Week 3

### ISSUE THREAD

**Issue by audip** [audip/Yelp#2]
My app is complete, as per user stories for week 3, please review. /cc @codepathreview

**Comment by minhchau273** [comment]
:+1: Nice work! This primary challenge of this homework was to learn how to use AutoLayout to build adaptive UI's that work across many different screen sizes and orientations. If you haven't already, we recommend going back and running your homework again while rotating the device / simulator to ensure your AutoLayout constraints function as expected.

### Some small comments:
- Nice work specifying the Auto Layout constraints.
- It's not a big deal but in case there is no result, you should show a label `No results found` to make your app more friendly :wink:
- It's a little weird when having the white gap at the top of `UITableView`.
  <img width="315" alt="screen shot 2016-02-14 at 3 44 37 pm" src="https://cloud.githubusercontent.com/assets/12395213/13032775/3a86f8b8-d332-11e5-85ac-eb06fe9e6374.png">
- **Infinite scroll for restaurant results** means when you scroll to the end of the table view, it will show the next 20 results. For now, you just reload the first 20 results.

We have a detailed [Project 3 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_3_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
